services:
  db:
    ports:
      - "5432:5432"
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - .env
    command: sh -c "poetry run alembic upgrade head && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8001"
    restart: on-failure

volumes:
  postgres_data: